### ISSUE TITLE
Extra spaces in unbound.conf.j2

### ISSUE THREAD

**Issue by kichay** [aruhier/ansible-role-unbound#10]
I have a bug with extra spaces in rendered unbound.conf.

My configuration is:
```
...
unbound_forward_zones:
  - name: "."
    forward-tls-upstream: "yes"
    forward-addr:
      - "1.1.1.1@853#one.one.one.one"
      - "1.0.0.1@853#one.one.one.one"
      - "8.8.8.8@853#dns.google"
      - "8.8.4.4@853#dns.google"
      - "9.9.9.9@853#dns.quad9.net"
      - "149.112.112.112@853#dns.quad9.net"
...
```

Rendered unbound.conf is:
```
...
forward-zone:
        forward-addr: 1.1.1.1@853#one.one.one.one
        forward-addr: 1.0.0.1@853#one.one.one.one
        forward-addr: 8.8.8.8@853#dns.google
        forward-addr: 8.8.4.4@853#dns.google
        forward-addr: 9.9.9.9@853#dns.quad9.net
        forward-addr: 149.112.112.112@853#dns.quad9.net
        name: .
    forward-tls-upstream: yes
...
```

I suppose there is buggy extra spaces here:
https://github.com/aruhier/ansible-role-unbound/blob/master/templates/unbound.conf.j2#L420
https://github.com/aruhier/ansible-role-unbound/blob/master/templates/unbound.conf.j2#L422
https://github.com/aruhier/ansible-role-unbound/blob/master/templates/unbound.conf.j2#L434
https://github.com/aruhier/ansible-role-unbound/blob/master/templates/unbound.conf.j2#L436
